### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by fotuzlab** [fourkitchens/saucier#1]
I installed and briefly explored the project. Looks promising! Thanks for sharing it with community.

I was wondering if it would be feasible at this stage to add some more documentation to the project - about how it helps in accelerating Headless Drupal implementation, step by step guide to implement a basic app with data fetched from API and probably a demo.

It will help in getting familiar with the project better.

**Comment by dcorb** [comment]
+1

**Comment by mattgrill** [comment]
@fotuzlab @dcorb Have a look at the same application I just released, https://github.com/fourkitchens/saucier-example. If you have any other issues I can reopen this ticket.
