### ISSUE TITLE
Missing Code or Documentation? 

### ISSUE THREAD

**Issue by bondydaa** [fourkitchens/saucier#6]
Maybe I am missing something but I can't seem to figure out how to actually use Saucier. The current master branch doesn't seem like a complete repo when you compare it to the version-one branch. I pulled the version-one branch down locally and merged in the code from master and tried to spin it up but that ended up leading me down a rabbit hole of out-of-date or missing gulp dependancies. 

Like I said, if I'm just missing something and all you need is the current master branch, plus saucier-get and saucier-cache awesome! Would love to know more about how to implement them to consume a decoupled d8 site.

Thanks!

**Comment by mattgrill** [comment]
@bondydaa Sorry about this. I've been distracted with other things. I've created a sample repo that should get you up to speed, https://github.com/fourkitchens/saucier-example.

If you have any issues let me know, and I can reopen this ticket.
